theme: jekyll-theme-minimal
title: Viet Name Detection Project
description: This is the page to publish the research and experiment about Vietnamese Name Detection.
copyright: VietSearch Global Technology Solution
